package com.shankyank.gradle.aws.apigateway.specification

/**
 * Converts Model definitions to a schema that can be read by API Gateway.
 */
interface SchemaConverter {
    /**
     * @return the content type of the schema generated by this converter
     */
    String getContentType()

    /**
     * Get the serialized schema for a named model in the input specification.
     * @param name the name of the model
     * @return the serialized schema for the named model
     */
    String getSchemaForNamedModel(final String name)

    /**
     * Generate a schema for the provided model.
     * @param name the name of the model
     * @param model the model
     * @return the serialized schema
     */
    String generateSchemaForModel(final String name, final Object model)
}
